apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wvtkby677-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wvtkby677-java-springboot-gitops